### ISSUE TITLE
Bugs in tests.py might happen if rebuild the db.

### ISSUE THREAD

**Issue by dreamATD** [Einsgate/SwIRL-Shared-Space#12]
I rebuilt the database and faced newly generated fails in the testcases. To fix that, I delete all objects in `Role`, `User`, `Team` and `TeamMember` models that used in team testcases and add my self-constructed ones. However, there might be the same problem in other testcases. 

Shall we take this into consideration?

**Comment by Einsgate** [comment]
0002_auto_20220314_1558.py was manually added. So, after changing models.py, you need to keep the 0002_auto_20220314_1558.py and remake 0001_initial.py (By deleting it and running ./manage.py makemigrations. Make sure you store 0002_auto_20220314_1558.py to somewhere else before you remake 0001_initial.py). After that, reset the database and run ./manage.py migrate to rebuild the database.
